(in-package #:coalton-native-tests)

(define-test ordmap-test ()
  (let ((declare to-list (ordmap:OrdMap Integer String
                                        -> List (Tuple Integer String)))
        (to-list (fn (m)
                   (the (List (Tuple Integer String))
                        (iter:collect! (iter:into-iter m)))))
        (declare from-list (List (Tuple Integer String)
                                 -> ordmap:OrdMap Integer String))
        (from-list (fn (xs)
                     (iter:collect!
                      (iter:into-iter
                       (the (List (Tuple Integer String)) xs))))))

    (is (== (ordmap:lookup (the (ordmap:OrdMap Integer String) ordmap:empty) 0)
            None))

    (is (== (let ((t (ordmap:insert ordmap:empty 0 "Zero")))
              (ordmap:lookup t 0))
            (Some "Zero")))

    (is (== (let ((t (ordmap:insert ordmap:empty 0 "Zero")))
              (ordmap:lookup t 1))
            None))

    (is (== (let ((t (ordmap:insert ordmap:empty 0 "Zero"))
                  (t2 (ordmap:insert t 0 "Null")))
              (ordmap:lookup t2 0))
            (Some "Null")))

    (is (== (let ((t (ordmap:insert ordmap:empty 0 "Zero"))
                  (t2 (ordmap:adjoin t 0 "Null")))
              (ordmap:lookup t2 0))
            (Some "Zero")))

    (is (== (let ((t (ordmap:insert ordmap:empty 0 "Zero"))
                  (t2 (ordmap:replace t 0 "Null")))
              (ordmap:lookup t2 0))
            (Some "Null")))

    (is (== (let ((t (ordmap:insert ordmap:empty 0 "Zero"))
                  (t2 (ordmap:replace t 1 "One")))
              (ordmap:lookup t2 1))
            None))

    (let ((src (the (ordmap:OrdMap Integer String)
                    (iter:collect!
                     (iter:into-iter
                      (make-list (Tuple 0 "Zero")
                                 (Tuple 1 "One")
                                 (Tuple 2 "Two"))))))
          (a (ordmap:remove src 1))
          (b (ordmap:remove src 3)))
      (is (== (make-list (ordmap:lookup a 0)
                         (ordmap:lookup a 1)
                         (ordmap:lookup a 2))
              (make-list (Some "Zero") None (Some "Two"))))
      (is (== (make-list (ordmap:lookup b 0)
                         (ordmap:lookup b 1)
                         (ordmap:lookup b 2))
              (make-list (Some "Zero") (Some "One") (Some "Two"))))

      (is (== (let ((t (ordmap:remove src 1))
                    (t2 (ordmap:remove t 2))
                    (t3 (ordmap:insert t2 1 "Eins")))
                (make-list (ordmap:lookup t3 0)
                           (ordmap:lookup t3 1)
                           (ordmap:lookup t3 2)))
              (make-list (Some "Zero") (Some "Eins") None))))

    (let ((src (from-list (make-list (Tuple 1 "One")
                                     (Tuple 2 "Two")
                                     (Tuple 3 "Three")
                                     (Tuple 4 "Four")
                                     (Tuple 5 "Five")
                                     (Tuple 6 "Six")
                                     (Tuple 7 "Seven")))))
      (is (== (let ((a (ordmap:insert src 10 "Zehn"))
                    (b (ordmap:remove a 3))
                    (c (ordmap:remove b 7))
                    (d (ordmap:insert c 8 "Acht"))
                    (e (ordmap:remove d 1))
                    (f (ordmap:remove e 10))
                    (g (ordmap:insert f 7 "Sieben"))
                    (h (ordmap:remove g 5)))
                (to-list h))
              (make-list (Tuple 2 "Two")
                         (Tuple 4 "Four")
                         (Tuple 6 "Six")
                         (Tuple 7 "Sieben")
                         (Tuple 8 "Acht")))))

    ;; update
    (let ((src (from-list (make-list (Tuple 1 "One")
                                 (Tuple 2 "Two")
                                 (Tuple 3 "Three")
                                 (Tuple 4 "Four")))))
      (is (== (match (ordmap:update src 4 (Tuple (Some "Quatre")))
                ((Tuple m v)
                 (Tuple (to-list m) v)))
              (Tuple (the (List (Tuple Integer String))
                          (make-list  (Tuple 1 "One")
                                      (Tuple 2 "Two")
                                      (Tuple 3 "Three")
                                      (Tuple 4 "Quatre")))
                     (Some "Four"))))
      (is (== (match (ordmap:update src 5 (Tuple (Some "Cinq")))
                ((Tuple m v)
                 (Tuple (to-list m) v)))
              (Tuple (the (List (Tuple Integer String))
                          (make-list  (Tuple 1 "One")
                                      (Tuple 2 "Two")
                                      (Tuple 3 "Three")
                                      (Tuple 4 "Four")
                                      (Tuple 5 "Cinq")))
                     None)))
      (is (== (match (ordmap:update src 3 (fn (v)
                                            (match v
                                              ((None) (Tuple (Some "Fill")
                                                             True))
                                              ((Some _) (Tuple v False)))))
                ((Tuple m v)
                 (Tuple (to-list m) v)))
              (Tuple (the (List (Tuple Integer String))
                          (make-list  (Tuple 1 "One")
                                      (Tuple 2 "Two")
                                      (Tuple 3 "Three")
                                      (Tuple 4 "Four")))
                     False)))
      (is (== (match (ordmap:update src 5 (fn (v)
                                            (match v
                                              ((None) (Tuple (Some "Fill")
                                                             True))
                                              ((Some _) (Tuple v False)))))
                ((Tuple m v)
                 (Tuple (to-list m) v)))
              (Tuple (the (List (Tuple Integer String))
                          (make-list  (Tuple 1 "One")
                                      (Tuple 2 "Two")
                                      (Tuple 3 "Three")
                                      (Tuple 4 "Four")
                                      (Tuple 5 "Fill")))
                     True))))

    ;; min/max key
    (let ((src (from-list (make-list (Tuple 1 "One")
                                     (Tuple 2 "Two")
                                     (Tuple 3 "Three")
                                     (Tuple 4 "Four")
                                     (Tuple 5 "Five")
                                     (Tuple 6 "Six")
                                     (Tuple 7 "Seven")))))
      (is (== (ordmap:max-key-entry src)
              (Some (Tuple 7 "Seven"))))
      (is (== (ordmap:min-key-entry src)
              (Some (Tuple 1 "One")))))
    (is (== (ordmap:max-key-entry (ordmap:insert ordmap:empty 1 "One"))
            (Some (Tuple 1 "One"))))
    (is (== (ordmap:min-key-entry (ordmap:insert ordmap:empty 1 "One"))
            (Some (Tuple 1 "One"))))
    (is (== (ordmap:max-key-entry (the (ordmap:OrdMap Integer String)
                                       ordmap:empty))
            None))
    (is (== (ordmap:min-key-entry (the (ordmap:OrdMap Integer String)
                                       ordmap:empty))
            None))

    ;; neighbors
    (let ((src (from-list (make-list (Tuple 1 "One")
                                     (Tuple 3 "Three")
                                     (Tuple 5 "Five")
                                     (Tuple 7 "Seven")
                                     (Tuple 9 "Nine")))))
      (is (== (ordmap:lookup-neighbors src 0)
              (Tuple3 None None (Some (Tuple 1 "One")))))
      (is (== (ordmap:lookup-neighbors src 1)
              (Tuple3 None (Some (Tuple 1 "One")) (Some (Tuple 3 "Three")))))
      (is (== (ordmap:lookup-neighbors src 2)
              (Tuple3 (Some (Tuple 1 "One")) None (Some (Tuple 3 "Three")))))
      (is (== (ordmap:lookup-neighbors src 3)
              (Tuple3 (Some (Tuple 1 "One")) (Some (Tuple 3 "Three")) (Some (Tuple 5 "Five")))))
      (is (== (ordmap:lookup-neighbors src 4)
              (Tuple3 (Some (Tuple 3 "Three")) None (Some (Tuple 5 "Five")))))
      (is (== (ordmap:lookup-neighbors src 5)
              (Tuple3 (Some (Tuple 3 "Three")) (Some (Tuple 5 "Five")) (Some (Tuple 7 "Seven")))))
      (is (== (ordmap:lookup-neighbors src 6)
              (Tuple3 (Some (Tuple 5 "Five")) None (Some (Tuple 7 "Seven")))))
      (is (== (ordmap:lookup-neighbors src 7)
              (Tuple3 (Some (Tuple 5 "Five")) (Some (Tuple 7 "Seven")) (Some (Tuple 9 "Nine")))))
      (is (== (ordmap:lookup-neighbors src 8)
              (Tuple3 (Some (Tuple 7 "Seven")) None (Some (Tuple 9 "Nine")))))
      (is (== (ordmap:lookup-neighbors src 9)
              (Tuple3 (Some (Tuple 7 "Seven")) (Some (Tuple 9 "Nine")) None)))
      (is (== (ordmap:lookup-neighbors src 10)
              (Tuple3 (Some (Tuple 9 "Nine")) None None))))

    ;; edge cases
    (is (== (ordmap:lookup-neighbors (the (ordmap:OrdMap Integer String)
                                          ordmap:Empty)
                                     1)
            (Tuple3 None None None)))
    (is (== (let ((a (ordmap:insert ordmap:Empty 1 "One")))
              (ordmap:lookup-neighbors a 1))
            (Tuple3 None (Some (Tuple 1 "One")) None)))
    ))
